# h2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

logging:
  level:
    com.wonzopein: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace